import type { Metadata } from 'next';
import './globals.css';
import Sidebar from '@/components/layouts/Sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// app/layout.tsx (イメージ)
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="bg-white text-black">
        <div className="flex min-h-screen max-w-[1000px] mx-auto">
          <Sidebar />

          {/* 右：メインコンテンツエリア */}
          <main className="flex-1 flex flex-col border-r border-gray-100">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
